import BbqPorkFriedRcie from "../assets/BbqPorkFriedRcie.jpg";
import BbqPorkNoodle from "../assets/BbqPorkNoodle.jpg";
import CrispyChickenSkewers from "../assets/CrispyChickenSkewers.jpg";
import CuminPotato from "../assets/CuminPotato.jpg";
import DeepFriedChickenWonton from "../assets/DeepFriedChickenWonton.jpg";
import DeepFriedSpringRolls from "../assets/DeepFriedSpringRolls.jpg";
import FriedDumplings from "../assets/FriedDumplings.jpg";
import PrawnFiredNoodle from "../assets/PrawnFiredNoodle.jpg";
import RoastedPorkBaoBuns from "../assets/RoastedPorkBaoBuns.jpg";
import SpcialFiredRice from "../assets/SpcialFiredRice.jpg";
import SteamedBbqPorkBuns from "../assets/SteamedBbqPorkBuns.jpg";
import TeriyakiChickenRice from "../assets/TeriyakiChickenRice.jpg";

export const ProductList = [
  {
    id: 1,
    name: "BBQ Pork Fried Rice",
    imgURL: BbqPorkFriedRcie,
    cat: "main",
    price: 14,
    spiciness: 0,
    isGF: true,
    isVegan: false,
    isAdded: false,
    qty: 0,
  },
  {
    id: 2,
    name: "BBQ Pork Noodle",
    imgURL: BbqPorkNoodle,
    cat: "main",
    price: 14,
    spiciness: 2,
    isGF: true,
    isVegan: false,
    isAdded: false,
    qty: 0,
  },
  {
    id: 3,
    name: "Crispy Chicken Skewers",
    imgURL: CrispyChickenSkewers,
    cat: "snack",
    price: 5,
    spiciness: 1,
    isGF: true,
    isVegan: false,
    isAdded: false,
    qty: 0,
  },
  {
    id: 4,
    name: "Cumin Potato",
    imgURL: CuminPotato,
    cat: "snack",
    price: 8,
    spiciness: 1,
    isGF: true,
    isVegan: true,
    isAdded: false,
    qty: 0,
  },
  {
    id: 5,
    name: "Deep Fried Chicken Wonton",
    imgURL: DeepFriedChickenWonton,
    cat: "snack",
    price: 4,
    spiciness: 0,
    isGF: true,
    isVegan: false,
    isAdded: false,
    qty: 0,
  },
  {
    id: 6,
    name: "Deep Fried Spring Rolls",
    imgURL: DeepFriedSpringRolls,
    cat: "snack",
    price: 4,
    spiciness: 0,
    isGF: true,
    isVegan: false,
    isAdded: false,
    qty: 0,
  },
  {
    id: 7,
    name: "Fried Dumplings",
    imgURL: FriedDumplings,
    cat: "snack",
    price: 8,
    spiciness: 0,
    isGF: false,
    isVegan: true,
    isAdded: false,
    qty: 0,
  },
  {
    id: 8,
    name: "Prawn Fired Noodle",
    imgURL: PrawnFiredNoodle,
    cat: "main",
    price: 14,
    spiciness: 1,
    isGF: true,
    isVegan: false,
    isAdded: false,
    qty: 0,
  },
  {
    id: 9,
    name: "Roasted Pork Bao Buns",
    imgURL: RoastedPorkBaoBuns,
    cat: "snack",
    price: 12,
    spiciness: 0,
    isGF: false,
    isVegan: false,
    isAdded: false,
    qty: 0,
  },
  {
    id: 10,
    name: "Spcial Fired Rice",
    imgURL: SpcialFiredRice,
    cat: "main",
    price: 14,
    spiciness: 3,
    isGF: true,
    isVegan: true,
    isAdded: false,
    qty: 0,
  },
  {
    id: 11,
    name: "Steamed BBQ Pork Buns",
    imgURL: SteamedBbqPorkBuns,
    cat: "main",
    price: 10,
    spiciness: 0,
    isGF: true,
    isVegan: false,
    isAdded: false,
    qty: 0,
  },
  {
    id: 12,
    name: "Teriyaki Chicken Rice",
    imgURL: TeriyakiChickenRice,
    cat: "main",
    price: 14,
    spiciness: 2,
    isGF: true,
    isVegan: false,
    isAdded: false,
    qty: 0,
  },
];
